config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "static_pages#root"
  resources :payment_methods
  resources :products
  resources :cart_items
  resources :orders
  resource :subscription do
    member do
      get :manage
    end
  end
  resource :marketplace

  get '/pricing', to: 'products#pricing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  pay_customer
  pay_merchant

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_many :cart_items

  after_commit :maybe_set_payment_processor

  def maybe_set_payment_processor
    if !self.pay_customers.present?
      set_payment_processor(:stripe)
    end
  end

  after_commit :maybe_set_merchant_processor

  def maybe_set_merchant_processor
    if !self.merchant_processor.present?
      set_merchant_processor(:stripe)
    end
  end

  def cart_count
    cart_items.sum(:quantity)
  end

  def cart_line_items
    cart_items.map do |cart_item|
      {
        quantity: cart_item.quantity,
        price: cart_item.price
      }
    end
  end

  def clear_cart!
    cart_items.destroy_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    @cart_item = current_user.cart_items.find_by(price: cart_item_params[:price])
    if @cart_item.nil?
      @cart_item = current_user.cart_items.create(cart_item_params)
    else
      @cart_item.quantity += cart_item_params[:quantity].to_i
      @cart_item.save
    end
    if !@cart_item.valid?
      flash[:error] = @cart_item.errors.full_messages.join(", ")
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:price, :quantity)
  end
end

app/controllers/marketplaces_controller.rb
class MarketplacesController < ApplicationController
  before_action :authenticate_user!

  def show

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    @checkout_session = current_user.payment_processor.checkout(
      mode: 'payment',
      line_items: current_user.cart_line_items,
      automatic_tax: {
        enabled: true
      },
      shipping_address_collection: {
        allowed_countries: ['US', 'CA', 'MX'],
      },
      customer_update: {
        shipping: 'auto',
        address: 'auto',
      },
      cancel_url: products_url,
    )
    redirect_to @checkout_session.url, allow_other_host: true, status: :see_other
  end
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @setup_intent = Stripe::SetupIntent.create(
      customer: current_user.pay_customers.first.customer.id,
      metadata: {
        user_id: current_user.id
      }
    )
  end

  def update
    @payment_method = current_user.pay_customers.first.payment_methods.find(params[:id])
    @payment_method.make_default!
    redirect_to payment_methods_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # One-time prices
  def index
    @products = Stripe::Price.list(
      active: true,
      type: 'one_time',
      currency: 'usd',
      expand: ['data.product'],
    )
  end

  # Recurring SaaS prices
  def pricing
    @products = Stripe::Price.list(
      active: true,
      type: 'recurring',
      currency: 'usd',
      lookup_keys: ['startup', 'freelancer', 'enterprise'],
      expand: ['data.product'],
    ).data.sort_by { |p| p.unit_amount }
    @products.each do |price|
      price.features = JSON.parse(price.product.metadata.features)
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!

  def root
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def create
    @checkout_session = current_user.payment_processor.checkout(
      mode: 'subscription',
      line_items: [{
        price: params[:price],
        quantity: 1,
      }],
      automatic_tax: {
        enabled: true
      },
      customer_update: {
        shipping: 'auto',
        address: 'auto',
      },
      cancel_url: pricing_url,
    )
    redirect_to @checkout_session.url, allow_other_host: true, status: :see_other
  end

  def show
    @subscription = current_user.payment_processor.subscription
    @price = Stripe::Price.retrieve(id: @subscription.processor_plan, expand: ['product'])
  end

  def manage
    portal_session = current_user.payment_processor.billing_portal(
      return_url: subscription_url,
    )

    redirect_to portal_session.url, allow_other_host: true, status: :see_other
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def top_menu_items
    [{
      name: 'Payment Methods',
      path: payment_methods_path,
    }, {
      name: 'One-time payments',
      path: products_path,
    }, {
      name: 'Recurring payments',
      path: '/pricing',
    }, {
      name: 'Customer portal',
      path: '/subscription',
    }, {
      name: 'Marketplace',
      path: '/marketplace',
    }]
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/marketplaces_helper.rb
module MarketplacesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>PayRailsDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= tag.meta name: "stripe-key", content: Pay::Stripe.public_key %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body class="h-full">
    <div class="min-h-full">
      <nav class="bg-white border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="flex justify-between h-16">
            <div class="flex">
              <div class="flex-shrink-0 flex items-center">
                <img class="block lg:hidden h-8 w-auto" src="https://raw.githubusercontent.com/pay-rails/pay/master/docs/images/logo.svg" alt="Workflow">
                <img class="hidden lg:block h-8 w-auto" src="https://raw.githubusercontent.com/pay-rails/pay/master/docs/images/logo.svg" alt="Workflow">
              </div>
              <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
                <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
                <% top_menu_items.each do |item| %>
                <a href="<%= item[:path] %>" class="<%= current_page?(item[:path]) ? 'border-indigo-500 text-gray-900' : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700' %> inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium" aria-current="page">
                  <%= item[:name] %>
                </a>
                <% end %>
              </div>
            </div>

            <div class="hidden sm:ml-6 sm:flex sm:items-center flow-root">
              <form action="/orders" method="post" data-turbo="false">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

                <button type="submit" class="flex bg-white p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  <span class="sr-only">View cart</span>
                  <svg class="flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                  </svg>
                  <span class="ml-2 text-sm font-medium"><%= current_user && current_user.cart_count %></span>
                </button>
              </form>

              <!-- Profile dropdown -->
              <div data-controller="menu" class="ml-3 relative">
                <div>
                  <button data-action="menu#toggleMenu" type="button" class="max-w-xs bg-white flex items-center text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                    <span class="sr-only">Open user menu</span>
                    <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                  </button>
                </div>

                <!--
                  Dropdown menu, show/hide based on menu state.

                  Entering: "transition ease-out duration-200"
                  From: "transform opacity-0 scale-95"
                  To: "transform opacity-100 scale-100"
                  Leaving: "transition ease-in duration-75"
                  From: "transform opacity-100 scale-100"
                  To: "transform opacity-0 scale-95"
                -->
                <div data-menu-target="dropdown" class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                  <a href="/users/sign_out" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">
                    Sign out
                  </a>
                </div>
              </div>
            </div>
            <div class="-mr-2 flex items-center sm:hidden">
              <!-- Mobile menu button -->
              <button type="button" class="bg-white inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <!--
                  Heroicon name: outline/menu

                  Menu open: "hidden", Menu closed: "block"
                -->
                <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
                <!--
                  Heroicon name: outline/x

                  Menu open: "block", Menu closed: "hidden"
                -->
                <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
        </div>

        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="sm:hidden" id="mobile-menu">
          <div class="pt-2 pb-3 space-y-1">
            <!-- Current: "bg-indigo-50 border-indigo-500 text-indigo-700", Default: "border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800" -->
            <a href="/payment_methods" class="bg-indigo-50 border-indigo-500 text-indigo-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium" aria-current="page">
              Payment Methods
            </a>

            <a href="#" class="border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">
              One-time payments
            </a>

            <a href="#" class="border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">
              Recurring payments
            </a>

            <a href="#" class="border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">
              Customer portal
            </a>
          </div>
          <div class="pt-4 pb-3 border-t border-gray-200">
            <div class="flex items-center px-4">
              <div class="flex-shrink-0">
                <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
              </div>
              <div class="ml-3">
                <div class="text-base font-medium text-gray-800">Tom Cook</div>
                <div class="text-sm font-medium text-gray-500">tom@example.com</div>
              </div>
              <button type="button" class="flex ml-auto bg-white flex-shrink-0 p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <span class="sr-only">View cart</span>
                <svg class="flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                </svg>
                <span class="ml-2 text-sm font-medium"><%= current_user && current_user.cart_count %></span>
              </button>
            </div>
            <div class="mt-3 space-y-1">
              <a href="/users/sign_out" class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">
                Sign out
              </a>
            </div>
          </div>
        </div>
      </nav>

      <div class="py-10">
        <header>
          <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold leading-tight text-gray-900">
              Demo
            </h1>
          </div>
        </header>
        <main>
          <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <!-- Replace with your content -->
            <div class="px-4 py-8 sm:px-0">
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
              <%= yield %>
            </div>
            <!-- /End replace -->
          </div>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/marketplaces/show.html.erb
<h1 class="text-3xl">Marketplace</h1>

TODO: Onboarding


TODO: Direct Charges


TODO: Destination Charges

app/views/pay/payments/show.html.erb
<div
  data-controller="payment-intent"
  data-payment-intent-client-secret-value="<%= @payment.client_secret %>"
  data-payment-intent-status-value="<%= @payment.status %>"
  data-payment-intent-customer-value="<%= @payment.customer %>"
  class="h-screen md:flex md:justify-center md:items-center">
  <div class="w-full max-w-lg">
    <!-- Status Messages -->
    <p data-payment-intent-target="error" class="hidden items-center mb-4 bg-red-100 border border-red-200 px-5 py-2 rounded-lg text-red-500">
      <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 text-red-500 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
      </svg>

      <span data-payment-intent-target="errorMessage" class="ml-3"></span>
    </p>

    <p data-payment-intent-target="success" class="hidden items-center mb-4 bg-green-100 border border-green-200 px-5 py-4 rounded-lg text-green-700">
      <svg xmlns="http://www.w3.org/2000/svg" class="flex-shrink-0 text-green-500 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
      </svg>

      <span data-payment-intent-target="successMessage" class="ml-3"></span>
    </p>

    <div class="bg-white rounded-lg shadow-xl p-4 sm:py-6 sm:px-10 mb-5">
      <% if @payment.succeeded? %>
        <h1 class="text-xl mt-2 mb-4 text-gray-700"><%=t "pay.successful.header" %></h1>
        <p class="mb-6"><%=t "pay.successful.description" %></p>

      <% elsif @payment.canceled? %>
        <h1 class="text-xl mt-2 mb-4 text-gray-700"><%=t "pay.cancelled.header" %></h1>
        <p class="mb-6"><%=t "pay.cancelled.description" %></p>

      <% else %>
        <div data-payment-intent-target="form" id="payment-elements">
          <!-- Instructions -->
          <h1 class="text-xl mt-2 mb-4 text-gray-700"><%=t "pay.requires_action.header", amount: @payment.amount_with_currency %></h1>
          <p class="mb-6"><%=t "pay.requires_action.description" %></p>

          <div data-payment-intent-target="cardFields" class="hidden">
            <!-- Name -->
            <label for="cardholder-name" class="inline-block text-sm text-gray-700 font-semibold mb-2"><%=t "pay.requires_action.full_name" %></label>
            <input data-payment-intent-target="name" id="cardholder-name" type="text" placeholder="Jane Doe" required autofocus class="mt-1 mb-6 block w-full px-3 py-2 rounded-md border border-gray-300 shadow-sm focus:outline-none focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50">

            <!-- Card -->
            <label for="card-element" class="inline-block text-sm text-gray-700 font-semibold mb-2"><%=t "pay.requires_action.card" %></label>
            <div data-payment-intent-target="card" id="card-element" class="mt-1 mb-6 block w-full px-3 py-4 rounded-md border border-gray-300 shadow-sm focus:outline-none focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"></div>
          </div>

          <!-- Pay Button -->
          <button data-payment-intent-target="button" data-action="click->payment-intent#confirmPayment" class="inline-block w-full px-4 py-3 mb-4 text-white rounded-lg bg-blue-400 hover:bg-blue-500">
            <%=t "pay.requires_action.button", amount: @payment.amount_with_currency %>
          </button>
        </div>
      <% end %>

      <%= link_to t("pay.back"), @redirect_to, class: "inline-block w-full px-4 py-3 bg-gray-100 hover:bg-gray-200 text-center text-gray-600 rounded-lg" %>
    </div>

    <p class="text-center text-gray-500 text-sm">
      © <%= Date.current.year %> <%= Pay.business_name %> <%=t "pay.all_rights_reserved" %>
    </p>
  </div>
</div>

<script type="module">
  window.stripe = Stripe('<%= Pay::Stripe.public_key %>');

  import { Application, Controller } from 'https://cdn.skypack.dev/@hotwired/stimulus'
  const application = Application.start()

  application.register('payment-intent', class extends Controller {
    static targets = ["error", "errorMessage", "success", "successMessage", "form", "button", "name", "card", "cardFields"]
    static values = {
      clientSecret: String,
      customer: String,
      status: String,
      errorMessage: String,
      successMessage: String,
      complete: Boolean,
      processing: Boolean
    }

    connect() {
      if (this.hasCardTarget) {
        this.elements = stripe.elements()
        this.cardElement = this.elements.create("card")
        this.cardElement.mount(this.cardTarget)
      }
    }

    statusValueChanged() {
      switch(this.statusValue) {
        case "requires_action":
          stripe.confirmCardPayment(this.clientSecretValue).then(this.handleConfirmResult.bind(this))
          break;
        case "requires_payment_method":
          this.cardFieldsTarget.classList.toggle("hidden", false)
          break;
      }
    }

    confirmPayment() {
      this.processingValue = true
      this.completeValue = false
      stripe.confirmCardPayment(this.clientSecretValue, {
        payment_method: {
          card: this.cardElement,
          billing_details: { name: this.nameTarget.value }
        },
        save_payment_method: this.customerValue != "",
        setup_future_usage: 'off_session',
      }).then(this.handleConfirmResult.bind(this))
    }

    handleConfirmResult(result) {
      this.processingValue = false

      if (result.error) {
        if (result.error.code === 'parameter_invalid_empty' &&
          result.error.param === 'payment_method_data[billing_details][name]') {
          this.errorMessageValue = '<%=t "pay.requires_action.name_missing" %>'
        } else {
          this.errorMessageValue = result.error.message
          this.statusValue = result.error.payment_intent.status
        }
      } else {
        this.completeValue = true;
        this.successMessageValue = '<%=t "pay.requires_action.success" %>'
      }
    }

    completeValueChanged() {
      if (this.hasFormTarget) {
        this.formTarget.classList.toggle("hidden", this.completeValue)
      }
    }

    processingValueChanged() {
      if (this.hasButtonTarget) {
        this.buttonTarget.disabled = this.processingValue
        this.buttonTarget.classList.toggle("bg-blue-400", this.processingValue)
        this.buttonTarget.classList.toggle("bg-blue-500", !this.processingValue)
      }
    }

    errorMessageValueChanged() {
      this.errorMessageTarget.textContent = this.errorMessageValue
      const enabled = (this.errorMessageValue != '')
      this.errorTarget.classList.toggle("flex", enabled)
      this.errorTarget.classList.toggle("hidden", !enabled)
    }

    successMessageValueChanged() {
      this.successMessageTarget.textContent = this.successMessageValue
      const enabled = (this.successMessageValue != '')
      this.successTarget.classList.toggle("flex", enabled)
      this.successTarget.classList.toggle("hidden", !enabled)
    }
  })
</script>

app/views/pay/stripe/_checkout_button.html.erb
<%= button_tag title,
  id: "checkout-#{session.id}",
  class: local_assigns[:class],
  style: (local_assigns[:class] || local_assigns[:style]) ? local_assigns[:style] : 'background-color:#6772E5;color:#FFF;padding:8px 12px;border:0;border-radius:4px;font-size:1em'
%>
<%= tag.div id: "error-for-#{session.id}" %>

<script>
  (() => {
    const checkoutButton = document.getElementById("checkout-<%= session.id %>");
    checkoutButton.addEventListener('click', function () {
      Stripe("<%= Pay::Stripe.public_key %>").redirectToCheckout({
        sessionId: '<%= session.id %>'
      }).then(function (result) {
        if (result.error) {
            document.getElementById("error-for-#{session.id}").innerText = result.error.message;
          }
      });
    });
  })()
</script>

app/views/payment_methods/index.html.erb
<h1 class="text-3xl">Payment Methods</h1>

<% if current_user.pay_customers.first.payment_methods.empty? %>
  <p>You have no payment methods, yet. Add one below to get started.</p>
<% end %>

<div>
  <div class="flow-root mt-6">
    <ul role="list" class="-my-5 divide-y divide-gray-200">
      <% current_user.pay_customers.first.payment_methods.each do |payment_method| %>
        <li class="py-4">
          <div class="flex items-center space-x-4">
            <div class="flex-shrink-0">
              <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1519345182560-3f2917c472ef?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </div>
            <div class="flex-1 min-w-0">
              <p class="text-sm font-medium text-gray-900 truncate">
                <%= payment_method.brand %> ending in <%= payment_method.last4 %>
              </p>
              <p class="text-sm text-gray-500 truncate">
                Exp: <%= payment_method.exp_month %>/<%= payment_method.exp_year %>
              </p>
            </div>
            <div>
              <% if payment_method.default? %>
                <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-green-100 text-green-800">Default</span>
              <% else %>
                <form action="<%= payment_method_path(payment_method) %>" method="post">
                  <input type="hidden" name="_method" value="PUT">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <button type="submit" class="inline-flex items-center shadow-sm px-2.5 py-0.5 border border-gray-300 text-sm leading-5 font-medium rounded-full text-gray-700 bg-white hover:bg-gray-50">
                    Make default
                  </button>
                </form>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<h2 class="text-xl mt-20">Add a payment method</h2>

<div class="grid grid-cols-2">
  <form data-controller="new-payment-method" data-action="new-payment-method#submit" data-new-payment-method-client-secret-value="<%= @setup_intent.client_secret %>" data-new-payment-method-return-url-value="<%= payment_methods_url %>" action="/payment_methods" method="post">

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="payment_method" value="">

    <div data-new-payment-method-target="paymentElement" id="payment-element"></div>

    <div class="pt-5">
      <div class="flex justify-end">
        <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          Save
        </button>
      </div>
    </div>

    <p class="text-red" data-new-payment-method-target="errors"></p>
  </form>
</div>

app/views/static_pages/root.html.erb
<h1 class="text-2xl">A demo of the <a class="underline text-blue-600 hover:text-blue-800 visited:text-purple-600" href="https://github.com/pay-rails/pay" target="_blank">pay</a> Ruby gem</h1>

<ul class="py-12">
  <li class="list-disc"><a class="underline text-blue-600 hover:text-blue-800 visited:text-purple-600" href="/payment_methods">List and add Payment Methods</a></li>
  <li class="list-disc"><a class="underline text-blue-600 hover:text-blue-800 visited:text-purple-600" href="/products">Accept one-time payments with Checkout</a></li>
  <li class="list-disc"><a class="underline text-blue-600 hover:text-blue-800 visited:text-purple-600" href="/pricing">Start a recurring subscription</a></li>
  <li class="list-disc"><a class="underline text-blue-600 hover:text-blue-800 visited:text-purple-600" href="/portal">Enable customers to manage billing</a></li>
</ul>